# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6c9dba0ce6cf50d8c1ae8c10240f3d7d19eec964258c9650a24e2dd2da715dd74811240ec111a1e2ade2a945127b542f84dc1c41e758534f98ff8adc69fd45c

test:
  secret_key_base: db4371660a88cb826e1b975b56209d01adde91c57b71850563da1c286414e2611eb55c5544eba447675154a7899a36e231a50c6d82f358b827f6b01125d1a4f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
